# Generated by Django 4.2.5 on 2023-09-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VloGoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='allprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(),
        ),
    ]
