# Generated by Django 4.2.5 on 2023-09-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VloGoApp', '0002_alter_cart_allprice_alter_cart_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.CharField(default='food', max_length=25),
            preserve_default=False,
        ),
    ]
